export type Tag = { id: string; name: string; category?: string };
export type Student = {
  id: string;
  name: string;
  username: string;
  college: string;
  collegeId: string;
  degree: string;
  year: number;
  bio: string;
  about: string;
  photo: string | null;
  verified: boolean;
  city: string;
  socialLinks: string[];
  goals: string[];
  hobbies: string[];
  careerInterests: string[];
  startupInterests: string[];
  interests: Tag[];
  skills: Tag[];
  explanation?: string;
  score?: number;
};
export type Settings = {
  showCity: boolean;
  showSocialLinks: boolean;
  discoverable: boolean;
  allowRequests: boolean;
  profileVisibility: "STUDENTS" | "CONNECTIONS";
  notifyMessages: boolean;
  notifyConnections: boolean;
};
export type Me = Student & {
  email: string;
  role: string;
  canPostEvents: boolean;
  completed: boolean;
  settings: Settings;
  verifications: { id: string; method: string; status: string }[];
};
export type Catalog = {
  colleges: { id: string; name: string }[];
  interests: Tag[];
  skills: Tag[];
};
export type Connection = {
  id: string;
  incoming: boolean;
  status: string;
  conversationId?: string;
  profile: Student;
};
export type Conversation = {
  id: string;
  kind: "DIRECT" | "GROUP";
  name?: string;
  ideaId?: string;
  members?: Student[];
  profile: Student;
  blocked: boolean;
  blockedByMe: boolean;
  unavailable: boolean;
  lastMessage?: string;
  unread: number;
};
export type Message = {
  id: string;
  senderId: string;
  conversationId: string;
  clientId: string;
  body: string;
  createdAt: string;
  removed: boolean;
  system?: boolean;
};
export type Idea = {
  id: string;
  authorId: string;
  title: string;
  description: string;
  category: string;
  lookingFor: string[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
  author: Student;
  resonanceCount: number;
  resonated: boolean;
};
export type CampusEvent = {
  id: string;
  creatorId: string;
  title: string;
  organizerName: string;
  description: string;
  category: string;
  startsAt: string;
  endsAt: string;
  timeZone: string;
  location: string;
  online: boolean;
  image: string | null;
  registrationUrl: string | null;
  capacity: number | null;
  createdAt: string;
  updatedAt: string;
  attendeeCount: number;
  going: boolean;
};
